<?php

namespace app\admin\controller;

use think\Controller;

class Article extends Controller
{
    protected $db;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Article();
    }

    public function index(){
        //每页显示10条数据
        $list = $this->db->getAll();
        $this->assign('list', $list);
        return $this->fetch();
    }


    /**
     * //添加栏目
     * @return mixed
     */
    public function addArt(){
        //判断post过来的数据
        if(request()->isPost()){
            // halt(input('post.'));
            $result = $this->db->addArt(input('post.'));
            if($result['valid']){
                //验证成功
                $this->success($result['msg'], 'index');exit;
            }else{
                //验证失败
                $this->error($result['msg']);
            }
        }
        $cateList = (new \app\common\model\Category())->getAll();
        $tagList = (new \app\common\model\Tag())->getAll();
        $this->assign('tag_list', $tagList);
        $this->assign('cate_list', $cateList);
        return $this->fetch();
    }



    /**
     * //编辑栏目
     * @return mixed
     */
    public function edit(){
        //判断post过来的数据
        if(request()->isPost()){
            // halt(input('post.'));exit;
            $result = $this->db->catEdit(input('post.'));
            if($result['valid']){
                //验证成功
                $this->success($result['msg'], 'index');
            }else{
                //验证失败
                $this->error($result['msg']);
            }
        }
        $cate_id = input('param.cate_id');
        $oldData = $this->db->where('cate_id', $cate_id)->find();
        // halt($oldData);
        //处理所属分类,不能包含子集和本身
        $cateList = $this->db->getPid($cate_id);
        $this->assign('cateList', $cateList);
        $this->assign('data', $oldData);
        return $this->fetch();
    }

    public function del(){
        $cate_id = input('param.cate_id');
        $result = $this->db->del($cate_id);
        if($result['valid']){
            //删除成功
            $this->success($result['msg'], 'index');
        }else{
            //删除失败
            $this->error($result['msg']);
        }
    }
}
