<?php

namespace app\admin\controller;

use think\Controller;

class Article extends Controller
{
    protected $db;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Article();
    }

    public function index(){
        //每页显示10条数据
        $list = $this->db->getAll(2);
        $this->assign('list', $list);
        return $this->fetch();
    }


    /**
     * //添加栏目
     * @return mixed
     */
    public function addArt(){
        //判断post过来的数据
        if(request()->isPost()){
            $result = $this->db->addArt(input('post.'));
            if($result['valid']){
                //验证成功
                $this->success($result['msg'], 'index');exit;
            }else{
                //验证失败
                $this->error($result['msg']);
            }
        }
        $cateList = (new \app\common\model\Category())->getAll();
        $this->assign('cate_list', $cateList);
        $tagList = (new \app\common\model\Tag())->getAll();
        $this->assign('tag_list', $tagList);
        return $this->fetch();
    }



    /**
     * //编辑栏目
     * @return mixed
     */
    public function edit(){
        //判断post过来的数据
        if(request()->isPost()){
            $result = $this->db->artEdit(input('post.'));
            if($result['valid']){
                //验证成功
                $this->success($result['msg'], 'index');
            }else{
                //验证失败
                $this->error($result['msg']);
            }
        }
        $arc_id = input('param.arc_id');
        //获取分类,默认显示现在所属分类
        $cateList = (new \app\common\model\Category())->getAll();
        $this->assign('cate_list', $cateList);
        //获取标签数据
        $tagList = (new \app\common\model\Tag())->getAll();
        $this->assign('tag_list', $tagList);
        //获取已选取的标签
        $result = $this->db->getTagList($arc_id);
        $this->assign('tag_select', $result);
        //获取文章数据

        $data = $this->db->getPost($arc_id);
        $this->assign('data', $data);
        // halt($data);exit;
        return $this->fetch();
    }

    public function del(){
        $arc_id = input('param.arc_id');
        if($this->db->save(['is_recycle'=>1],['arc_id'=>$arc_id])){
            $this->success('删除成功', 'index');
        }else{
            $this->error('删除失败');
        }
    }

    public function recycle(){
        //每页显示10条数据
        $list = $this->db->getAll(1);
        $this->assign('list', $list);
        return $this->fetch();
    }

    //撤销删除,恢复文章到文章列表
    public function revert(){
        $arc_id = input('param.arc_id');
        if($this->db->save(['is_recycle'=>2],['arc_id'=>$arc_id])){
            $this->success('恢复成功', 'recycle');
        }else{
            $this->error('恢复失败');
        }
    }

    public function eraser(){
        $arc_id = input('param.arc_id');
        if($this->db->save(['is_recycle'=>0],['arc_id'=>$arc_id])){
            $this->success('彻底删除成功', 'recycle');
        }else{
            $this->error('彻底删除失败');
        }
    }
}
