<?php

namespace app\admin\controller;

use think\Controller;


/**
 * Class Category
 * 栏目管理控制器
 * @package app\admin\controller
 */

class Category extends Controller
{
    protected $db;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Category();
    }

    //栏目列表
    public function index(){
        //提交过来的请求信息是post,连接数据库获取类型列表
        if(request()->isPost()){
            $catList = (new Category())->catList();
            // dump($catList);exit();
            $this->assign('list', $catList);
        }
        return $this->fetch();
    }

    //添加栏目
    public function addcat(){
        //判断post过来的数据
        if(request()->isPost()){
            // halt(input('post.'));
            $result = $this->db->catadd(input('post.'));
            if($result['valid']){
                    //验证成功
                    $this->success($result['msg'], 'index');exit;
            }else{
                    //登录失败
                    $this->error($result['msg']);exit;
            }
        }
        return $this->fetch();
    }
}
