<?php

namespace app\admin\controller;

use think\Controller;

class Link extends Controller
{
    protected $db;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Link();
    }
    //友链首页
    public function index(){
        $list = (new \app\common\model\Link())->getAll();
        $this->assign('list',$list);
        return $this->fetch();
    }

    public function edit(){
        if(request()->isPost()){
            // halt(input('post.'));exit;
            $result = $this->db->linkEdit(input('post.'));
            if($result['valid']){
                //验证成功
                $this->success($result['msg'], 'index');
            }else{
                //验证失败
                $this->error($result['msg']);
            }
        }
        $result = $this->db->where('link_id',input('param.link_id'))->find();
        $this->assign('data', $result);
        return $this->fetch();
    }

    public function addLink(){
        if(request()->isPost()){
            $result = $this->db->addLink(input('post.'));
            if($result['valid']){
                //验证成功
                $this->success($result['msg'], 'index');
            }else{
                //验证失败
                $this->error($result['msg']);
            }
        }
        return $this->fetch();
    }

    public function del(){
        $link_id = input('param.link_id');
        $result = $this->db->del((int)$link_id);
        if($result['valid']){
            //删除成功
            $this->success($result['msg'], 'index');
        }else{
            //删除失败
            $this->error($result['msg']);
        }
    }
}
