<?php

namespace app\admin\controller;

use think\Controller;

class Tag extends Controller
{
    protected $db;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Tag();
    }

    public function index(){
        //每页显示10条数据
        $tagList = $this->db->getAll(10);
        $this->assign('list', $tagList);
        return $this->fetch();
    }

    public function edit(){
        if(request()->isPost()){
            // halt(input('post.'));exit;
            $result = $this->db->tagEdit(input('post.'));
            if($result['valid']){
                //验证成功
                $this->success($result['msg'], 'index');
            }else{
                //验证失败
                $this->error($result['msg']);
            }
        }
        $result = $this->db->where('tag_id',input('param.tag_id'))->find();
        // halt($result);exit;
        $this->assign('data', $result);
        return $this->fetch();
    }

    public function addTag(){
        if(request()->isPost()){
            $result = $this->db->addTag(input('post.'));
            if($result['valid']){
                //验证成功
                $this->success($result['msg'], 'index');
            }else{
                //验证失败
                $this->error($result['msg']);
            }
        }
        return $this->fetch();
    }

    public function del(){
        $tag_id = input('param.tag_id');
        $result = $this->db->del((int)$tag_id);
        if($result['valid']){
            //删除成功
            $this->success($result['msg'], 'index');
        }else{
            //删除失败
            $this->error($result['msg']);
        }
    }



}
