<?php

namespace app\admin\controller;

use think\Controller;

class Webset extends Controller
{
    //
    protected $db;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Webset();
    }

    public function index(){
        $webSetList = $this->db->getAll(7);
        $this->assign('list', $webSetList);
        return $this->fetch();
    }

    public function edit(){
        if(request()->isAjax()){
            $result = (new \app\common\model\Webset())->edit(input('post.'));
            if($result['valid']){
                //验证成功
                $this->success($result['msg'], 'index');
            }else{
                //验证失败
                $this->error($result['msg']);
            }
        }
    }
}
