<?php
namespace app\index\controller;


class Index extends Common
{
    protected $db;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db = new \app\common\model\Index();
        $headName = $this->loadWebSet()['title'] . '--首页';
        $this->assign('headName',$headName);
    }

    public function index()
    {
        $data = $this->db->getArt(2,2);
        // halt($data);exit;
        $this->assign('data', $data);
        return $this->fetch();
    }




}
